### ISSUE TITLE
Copy Pasta errors

### ISSUE THREAD

**Issue by jpero09** [n8io/apollo#1]
Search and replace 'utopias' and 'hello-world' references.

**Comment by n8io** [comment]
Done. Just curious, why you are interested in this repo?

**Comment by jpero09** [comment]
Initially thought it was a quick and dirty heartbeat dashboard. Just checking it out to see what it was. Got it to run on my local and all i saw the home route was a heartbeat-like json response, so...stepping away until I see you to discuss further IRL.
